# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end
  
  lane :build_and_export do
    # xcversion(version: "13.2.1")
    gym
    
    google_app_id = get_info_plist_value(
        path: "CatsAndModules_DmytroHetman/GoogleService-Info.plist",
        key: "GOOGLE_APP_ID"
    )
    
    firebase_app_distribution(
        app: google_app_id,
        testers: "n.marhal@ukma.edu.ua"
    )
  end
  
  lane :take_screenshots do
    capture_screenshots
  end
end
